[package]
name = "yurtc"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "yurtc"
path = "src/lib.rs"

[[bin]]
name = "yurtc"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
ariadne = { workspace = true }
chumsky = { workspace = true }
clap = { workspace = true }
expect-test = { workspace = true }
itertools = { workspace = true }
logos = { workspace = true }
num-bigint = "0.4"
num-traits = "0.2"
regex = "1.9"
thiserror = { workspace = true }
yansi = { workspace = true }
