[package]
name = "yurtc"
version = "0.1.0"
edition = "2021"

[lib]
name = "yurtc"
path = "src/lib.rs"

[[bin]]
name = "yurtc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
ariadne = "0.3"
chumsky = "0.9"
clap = { version = "4.3", features = ["cargo"] }
expect-test = "1.4"
itertools = "0.11"
logos = "0.13"
num-bigint = "0.4"
num-traits = "0.2"
regex = "1.9"
thiserror = "1.0"
