[package]
name = "yurtfmt"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
ariadne = "0.3"
chumsky = { workspace = true }
clap = { version = "4.3", features = ["cargo"] }
expect-test = "1.4"
itertools = "0.11"
logos = { workspace = true }
thiserror = "1.0"
