version: 2
updates:
  - package-ecosystem: cargo
    directory: /yurtc/
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
