[workspace]
resolver = "2"
members = ["yurtc", "yurtfmt"]

[workspace.dependencies]
yansi = "0.5"
anyhow = "1.0"
ariadne = "0.3"
chumsky = "0.9"
clap = { version = "4.4", features = ["cargo"] }
expect-test = "1.4"
itertools = "0.11"
logos = "0.13"
thiserror = "1.0"

[workspace.package]
edition = "2021"
authors = ["Essential Contributions <contact@essentialcontributions.com>"]
homepage = "https://essential.builders/"
license = "Apache-2.0"
repository = "https://github.com/essential-contributions/yurt"
