[workspace]
resolver = "2"
members = ["yurt-solve", "yurtc", "yurtfmt", "tests", "test-util"]

[workspace.dependencies]
yansi = "0.5"
anyhow = "1.0"
ariadne = "0.4"
chumsky = "0.9"
clap = { version = "4.5", features = ["derive"] }
expect-test = "1.4"
itertools = "0.12"
logos = "0.14"
thiserror = "1.0"
constraint-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git", package = "essential-constraint-asm" }
state-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git", package = "essential-state-asm" }
essential-types = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }

[workspace.package]
edition = "2021"
authors = ["Essential Contributions <contact@essentialcontributions.com>"]
homepage = "https://essential.builders/"
license = "Apache-2.0"
repository = "https://github.com/essential-contributions/yurt"
