[workspace]
resolver = "2"
members = [
  "abi-types",
  "examples",
  "pint",
  "pint-manifest",
  "pint-pkg",
  "pint-solve",
  "pintc",
  "pintfmt",
  "test-util",
  "tests",
]

[workspace.dependencies]
yansi = "1.0"
anyhow = "1.0"
ariadne = "0.4"
chumsky = "0.9"
clap = { version = "4.5", features = ["derive"] }
constraint-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git", package = "essential-constraint-asm" }
essential-hash = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-types = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
expect-test = "1.4"
fxhash = "0.2"
itertools = "0.12"
logos = "0.14"
petgraph = "0.6"
pint-manifest = { path = "pint-manifest" }
pint-pkg = { path = "pint-pkg" }
pintc = { path = "pintc" }
serde = { version = "1", features = ["derive"] }
serde_ignored = "0.1"
serde_json = "1"
state-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git", package = "essential-state-asm" }
thiserror = "1.0"
toml = "0.8"
walkdir = "2.5"

[workspace.package]
edition = "2021"
authors = ["Essential Contributions <contact@essentialcontributions.com>"]
homepage = "https://essential.builders/"
license = "Apache-2.0"
repository = "https://github.com/essential-contributions/pint"
