# Autoformatter friendly markdownlint config (all formatting rules disabled)
default: true
blank_lines: false
bullet: false
html: false
indentation: false
line_length: false
spaces: false
url: false
whitespace: false
MD026: false # Allow trailing punctuation in heading
MD041: false # Allow first line in a file to not be a top-level heading
MD014: false # Allow dollar signs to be used before commands
