[package]
name = "pint-abi-types"
version = "0.3.0"
description = "A crate containing the types used in the Pint ABI"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
