[book]
authors = ["Essential Contributions <contact@essentialcontributions.com> "]
language = "en"
multilingual = false
src = "src"
title = "Pint Specification"

[output.html]
additional-js = ["theme/pint.js", "theme/bnf.js"]
git-repository-url = "https://github.com/essential-contributions/pint"

[preprocessor.katex]
after = ["links"]
