name: cache-trunk
run-name: Caches on Trunk configuration change

on:
  push:
    branches: [master]
    paths: [.trunk/trunk.yaml]
  workflow_dispatch: {}

permissions: read-all

jobs:
  cache-trunk:
    name: Cache Trunk
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Provide Access to Private Repos
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: populate_cache_only
