name: ci
run-name: Checks on pull request

on:
  push:
    branches: [master]
  pull_request: null

env:
  RUST_VERSION: 1.72.0
  NIGHTLY_RUST_VERSION: nightly-2023-07-01

jobs:
  trunk-check:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1

  build:
    name: Cargo Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - uses: Swatinem/rust-cache@v2

      - name: Build Workspace
        run: cargo build --release

  cargo-unused-deps-check:
    name: Cargo Unused Dependencies Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_RUST_VERSION }} # `cargo-udeps` requires nightly to run

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-udeps
        run: cargo install --locked cargo-udeps

      - name: Check Unused Deps
        run: cargo udeps --locked --all-targets

  cargo-toml-lint-check:
    name: Cargo.toml Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - uses: Swatinem/rust-cache@v2

      - name: Install Cargo.toml linter
        run: cargo install --locked cargo-toml-lint

      - name: Run Cargo.toml linter
        run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint

  cargo-test-workspace:
    name: Cargo Test Workspace Using nextest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-nextest
          locked: true

      - name: Run workspace tests
        run: cargo nextest run --release --locked
