name: Weekly Update

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * 0" # yamllint disable-line rule:quoted-strings
  workflow_dispatch: {}

permissions: read-all

jobs:
  trunk-upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    permissions:
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1
        with:
          base: master

      - name: Notify Slack
        if: failure()
        run: |
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MSG_TEXT="Weekly job failed! Check the run here: $RUN_URL"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$MSG_TEXT"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
