name: Weekly Update

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * 0" # yamllint disable-line rule:quoted-strings
  workflow_dispatch: {}

permissions: read-all

jobs:
  trunk-upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    permissions:
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1
        with:
          base: master
